src/DW/UserBundle/Entity/Cin.php
<?php

namespace DW\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="cins")
 * @ORM\HasLifecycleCallbacks
 */
class Cin {

    /**
     * @var integer $id
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(name="cert_name", type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     *
     * @ORM\ManyToOne(targetEntity="DW\UserBundle\Entity\User", inversedBy="cins", cascade={"persist"})
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=false, onDelete="CASCADE")
     *
     * @var User
     */
    private $user;

    /**
     * @var UploadedFile $cinFile
     */
    private $cinFile;

    /**
     * Cin constructor.
     */
    public function __construct(UploadedFile $file)
    {
        $this->createdAt = new \DateTime();
        $this->setCinFile($file);
    }


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Cin
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return Cin
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set user
     *
     * @param \DW\UserBundle\Entity\User $user
     *
     * @return Cin
     */
    public function setUser(\DW\UserBundle\Entity\User $user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return UploadedFile
     */
    public function getCinFile()
    {
        return $this->cinFile;
    }

    /**
     * @param UploadedFile $cinFile
     */
    public function setCinFile($cinFile)
    {
        $this->cinFile = $cinFile;
    }

    /**
     * Get user
     *
     * @return \DW\UserBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    public function getAbsolutePath()
    {
        return null === $this->name
            ? null
            : $this->getUploadRootDir().'/'.$this->name;
    }

    public function getWebPath()
    {
        return null === $this->name
            ? null
            : $this->getUploadDir().'/'.$this->name;
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    protected function getUploadDir()
    {
        return 'uploads/users/cins';
    }


    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if (null === $this->getCinFile()) {
            return;
        }

        $this->getCinFile()->move($this->getUploadRootDir(), $this->getName());
        $this->cinFile = null;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        $file = $this->getAbsolutePath();
        if ($file) {
            unlink($file);
        }
    }
}

src/DW/UserBundle/Controller/Dashboard/ProfileController.php
<?php


namespace DW\UserBundle\Controller\Dashboard;

use DW\UserBundle\Entity\Certification;
use DW\UserBundle\Entity\CurriculumVitae;
use DW\UserBundle\Entity\User;
use DW\UserBundle\Entity\UserAddress;
use DW\UserBundle\Event\UserEvent;
use DW\UserBundle\Event\UserEvents;
use DW\UserBundle\Form\CertificationType;
use DW\UserBundle\Form\Type\ProfileContactFormType;
use DW\UserBundle\Form\Type\ProfilePaymentFormType;
use DW\UserBundle\Form\Type\ProfileSwitchFormType;
use FOS\UserBundle\Model\UserInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

/**
 * Class ProfileController
 *
 * @Route("/user")
 */
class ProfileController extends Controller
{

    /**
     * Edit user profile
     *
     * @Route("/edit-about-me", name="dw_user_dashboard_profile_edit_about_me")
     * @Method({"GET", "POST"})
     *
     * @param $request Request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function editAboutMeAction(Request $request)
    {
        /** @var User $user */
        $user = $this->getUser();
        if (!is_object($user) || !$user instanceof UserInterface) {
            throw new AccessDeniedException('This user does not have access to this section.');
        }

        $form = $this->createEditAboutMeForm($user);
        $form->handleRequest($request);
        //dump($form->getData());die;
        if ($form->isSubmitted() && $form->isValid()) {
            if($form->getData()->getImage()){
                if($user->getImage()->getUser() === null){
                    $user->getImage()->setUser($user);
                }
                $form->getData()->getImage()->upload();
            }

            $this->get("dw_user.user_manager")->updateUser($user);
            $this->container->get('session')->getFlashBag()->add(
                'success',
                $this->container->get('translator')->trans('user.edit.about_me.success', array(), 'dw_user')
            );

            $url = $this->generateUrl('dw_user_dashboard_profile_edit_about_me');

            return new RedirectResponse($url);
        }

        return $this->container->get('templating')->renderResponse(
            'DWUserBundle:Dashboard/Profile:edit_about_me.html.twig',
            array(
                'form' => $form->createView(),
                'user' => $user
            )
        );

    }


    /**
     * Creates a form to edit a user entity.
     *
     * @param mixed $user
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createEditAboutMeForm($user)
    {
        $form = $this->get('form.factory')->createNamed(
            'user',
            'user_profile_about_me',
            $user,
            array(
                'method' => 'POST',
                'action' => $this->generateUrl('dw_user_dashboard_profile_edit_about_me'),
            )
        );

        return $form;
    }


    /**
     * Edit user profile
     *
     * @Route("/edit-payment", name="dw_user_dashboard_profile_edit_payment")
     * @Method({"GET", "POST"})
     *
     * @param $request Request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function editPaymentAction(Request $request)
    {
        $user = $this->getUser();
        if (!is_object($user) || !$user instanceof UserInterface) {
            throw new AccessDeniedException('This user does not have access to this section.');
        }

        $form = $this->createEditPaymentForm($user);
        $success = $this->get('dw_user.form.handler.edit_payment')->process($form);

        $session = $this->container->get('session');
        $translator = $this->container->get('translator');

        if ($success > 0) {
            $session->getFlashBag()->add(
                'success',
                $translator->trans('user.edit.payment.success', array(), 'dw_user')
            );

            return $this->redirect(
                $this->generateUrl(
                    'dw_user_dashboard_profile_edit_payment'
                )
            );
        } elseif ($success < 0) {
            $session->getFlashBag()->add(
                'error',
                $translator->trans('user.edit.payment.error', array(), 'dw_user')
            );
        }

        return $this->render(
            'DWUserBundle:Dashboard/Profile:edit_payment.html.twig',
            array(
                'form' => $form->createView(),
                'user' => $user
            )
        );
    }

    /**
     * Creates a form to edit a user entity.
     *
     * @param mixed $user
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createEditPaymentForm($user)
    {
        $form = $this->get('form.factory')->createNamed(
            'user',
            new ProfilePaymentFormType(),
            $user,
            array(
                'method' => 'POST',
                'action' => $this->generateUrl('dw_user_dashboard_profile_edit_payment'),
            )
        );

        return $form;
    }


    /**
     * Edit user profile
     *
     * @Route("/edit-contact", name="dw_user_dashboard_profile_edit_contact")
     * @Method({"GET", "POST"})
     *
     * @param $request Request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function editContactAction(Request $request)
    {
        $user = $this->getUser();
        if (!is_object($user) || !$user instanceof UserInterface) {
            throw new AccessDeniedException('This user does not have access to this section.');
        }

        $form = $this->createEditContactForm($user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $session = $this->get('session');

            //Eventually change user profile data before update it
            $event = new UserEvent($user);
            $this->get('event_dispatcher')->dispatch(UserEvents::USER_PROFILE_UPDATE, $event);
            $user = $event->getUser();
//            $result = $event->getResult();

            $this->get("dw_user.user_manager")->updateUser($user);

            $session->getFlashBag()->add('success', $this->get('translator')->trans('user.edit.contact.success', array(), 'dw_user'));

//            if(is_array($result) && !empty($result)) {
//                $session->getFlashBag()->add($result['type'], $result['msg']);
//            }

            return $this->redirect($this->generateUrl('dw_user_dashboard_profile_edit_contact'));
        }

        return $this->render(
            'DWUserBundle:Dashboard/Profile:edit_contact.html.twig',
            array(
                'form' => $form->createView(),
                'user' => $user
            )
        );
    }

    /**
     * Creates a form to edit a user entity.
     *
     * @param mixed $user
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createEditContactForm($user)
    {
        $addresses = $user->getAddresses();
        if (count($addresses) == 0) {
            $user->addAddress(new UserAddress());
        }
        $form = $this->get('form.factory')->createNamed(
            'user',
            new ProfileContactFormType(),
            $user,
            array(
                'method' => 'POST',
                'action' => $this->generateUrl('dw_user_dashboard_profile_edit_contact'),
            )
        );


        return $form;
    }

    /**
     * Edit user profile
     *
     * @Route("/certification", name="dw_user_dashboard_profile_certification")
     * @Method({"GET", "POST"})
     *
     * @param $request Request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function certificationAction(Request $request)
    {
        $user = $this->getUser();
        if (!is_object($user) || !$user instanceof UserInterface) {
            throw new AccessDeniedException('This user does not have access to this section.');
        }

        $certification = new Certification();

        $form = $this->createCertificationForm($certification);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $em = $this->getDoctrine()->getManager();

            if(null !== $certification->getTitle()) {
                $certification->setUser($user);
                $em->persist($certification);

            }

            $cvFile = $request->files->get($form->getName())['cv']['path'];

            if(null !== $cvFile) {
                $cv = new CurriculumVitae();
                if(null !== $user->getCv()) {
                    $cv = $user->getCv();
                }
                $cv->setUser($user);
                $cv->setPath($cvFile);
                $em->persist($cv);
            }

            $em->flush();

            $this->container->get('session')->getFlashBag()->add(
                'success',
                $this->container->get('translator')->trans('user.edit.about_me.success', array(), 'dw_user')
            );

            $url = $this->generateUrl('dw_user_dashboard_profile_certification');

            return new RedirectResponse($url);
        }

        return $this->render('DWUserBundle:Dashboard/Profile:certification.html.twig',[
            'form' => $form->createView(),
            'user' => $user
        ]);

    }

    /**
     * Creates a form to certification user
     *
     * @param mixed $certification
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCertificationForm($certification)
    {

src/DW/UserBundle/Controller/Frontend/ProfileController.php
<?php

namespace DW\UserBundle\Controller\Frontend;

use DW\CoreBundle\Entity\Listing;
use DW\CoreBundle\Repository\ListingRepository;
use DW\UserBundle\Entity\User;
use FOS\UserBundle\Model\UserInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\DependencyInjection\ContainerAware;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

/**
 * Controller managing the user profile
 *
 * @Route("/user")
 */
class ProfileController extends ContainerAware
{
    /**
     * Show user profile
     *
     * @Route("/{id}/show", name="dw_user_profile_show", requirements={
     *      "id" = "\d+"
     * })
     * @Method("GET")
     * @ParamConverter("user", class="DWUserBundle:User")
     *
     * @param  Request $request
     * @param  User    $user
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */

    public function showAction(Request $request, User $user,$page = 1)
    {
        if (!is_object($user) || !$user instanceof UserInterface) {
            throw new AccessDeniedException('This user does not have access to this section.');
        }

        $em = $this->container->get('doctrine')->getManager();
        /** @var ListingRepository $listingRepository */
        $listingRepository = $em->getRepository('DWCoreBundle:Listing');
        $userListings = $listingRepository->findByOwner(
            $user->getId(),
            array(Listing::STATUS_PUBLISHED)
        );

        $reviewManager = $this->container->get('dw.review.manager');
        $reviewsReceived = $reviewManager->getUserReviews(null, $user, 'received');

        return $this->container->get('templating')->renderResponse(
            'DWUserBundle:Frontend/Profile:show.html.twig',
            array(
                'user' => $user,
                'user_listings' => $userListings,
                'reviews_received' => $reviewsReceived,
                'pagination' => array(
                    'page' => $page,
                    'pages_count' => ceil($reviewsReceived->count() / 10),
                    'route' => $request->get('_route'),
                    'route_params' => $request->query->all()
                ),
            )
        );
    }


}

src/DW/UserBundle/Resources/views/Dashboard/Profile/_completion_notice.html.twig
{% trans_default_domain 'dw_user' %}

<!-- alert -->
<div class="notification warning">
    <p>
        <i class="fa fa-warning"></i>

    </p>
</div>

src/DW/UserBundle/Resources/views/Dashboard/Profile/_nav_side.html.twig
{% trans_default_domain 'dw_user' %}
<div class="dashboard-nav" style="position: relative;">
    <div class="dashboard-nav-inner">
        <ul data-submenu-title="{{ 'nav.dashboard.profile.link'|trans({},'dw') }}">
            <li class="{{ nav_side_dashboard_current == "about_me" ? 'active' : '' }}">
                <a href="{{ path('dw_user_dashboard_profile_edit_about_me') }}">
                    <i class="fa fa-rss"></i>
                    {{ 'nav.user.about_me.link'|trans }}
                </a>
            </li>
            <li class="{{ nav_side_dashboard_current == "contact" ? 'active' : '' }}">
                <a href="{{ path('dw_user_dashboard_profile_edit_contact') }}">
                    <i class="fa fa-list-ul"></i>
                    {{ 'nav.user.contact.link'|trans }}
                </a>
            </li>
            <li class="{{ nav_side_dashboard_current == "payment" ? 'active' : '' }}">
                <a href="{{ path('dw_user_dashboard_profile_edit_payment') }}">
                    <i class="fa fa-money"></i>
                    {{ 'nav.user.payment.link'|trans }}
                </a>
            </li>
            <li class="{{ nav_side_dashboard_current == "certification" ? 'active' : '' }}">
                <a href="{{ path('dw_user_dashboard_profile_certification') }}">
                    <i class="fa fa-mortar-board"></i>
                    {{ 'nav.user.cert_cv.link'|trans }}
                </a>
            </li>
            <li>
                <a target="_blank" href="{{ path('dw_user_profile_show', {'id': app.user.id }) }}" >
                    <i class="fa fa-eye"></i>
                    {{ 'nav.user.show.link'|trans }}
                </a>
            </li>
        </ul>
    </div>
</div>

src/DW/UserBundle/Resources/views/Dashboard/Profile/certification.html.twig
{% extends '@DWCore/Dashboard/Listing/layout.html.twig' %}

{% trans_default_domain 'dw_user' %}

{% block nav_dashboard -%}
    {% set nav_dashboard_current = 'profile' %}
    {{ parent() }}
{%- endblock %}

{% block page_header %}
    {% include "DWCoreBundle:Dashboard/Common:_page_header.html.twig" with {
    'title': 'nav.dashboard.profile.link'|trans({}, 'dw'),
    'sub': 'Certification',
    'crumb': 'Certification'
    } only %}
{% endblock %}

{% block nav_side_dashboard -%}
    {% include '@DWUser/Dashboard/Profile/_nav_side.html.twig' with {
    'nav_side_dashboard_current': 'certification'
    } only %}
{%- endblock %}

{% block content_dashboard %}
{{ form_start(form) }}
    {% include 'DWCoreBundle:Frontend/Common:_flash.html.twig' %}
    {{ form_errors(form) }}
    <div class="dashboard-list-box">
        <h4 class="gray">{#Certification / Curriculum Vitae#}{{ 'nav.user.cert_cv.link'|trans }}</h4>
        <div class="dashboard-list-box-static">

            <!-- Details -->
            <div class="my-profile">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">{{ form_row(form.title,{'label_attr':{'class':'margin-top-0'}}) }}</div>
                        <div class="col-md-12">
                            {#{% set image_user = app.user.image ? app.user.image.name : UserImageConstants.IMAGE_DEFAULT %}#}
                            <img id="image_file" height="220" style="width: 100%;"/>

                            {#
                                <span><i class="fa fa-upload"></i> Upload Cert</span>
                                {{ form_widget(form.path,{'attr': {'class': 'upload'}} ) }}#}
                            {{ form_widget(form.path,{'attr':{'class':'inputfile novalidate'}}) }}
                            {{ form_label(form.path, '', {'label_attr':{'class':'button margin-top-10'}}) }}
                        </div>
                        {{ form_errors(form.path) }}
                    </div>
                </div>
                <div class="col-md-6">
                    {% if user.certifications|length > 0 %}
                        <div class="row">
                        {% for k, cert in user.certifications %}
                            {% if k != 0 and k % 2 == 0 %}</div><hr><div class="row">{% endif %}
                            <div class="col-md-6">
                                <a href="{{ asset(cert.webPath) }}" data-lightbox="image-{{ k }}" data-title="{{ cert.title }}">
                                    <img src="{{ asset(cert.webPath) }}" alt="{{ cert.title }}">
                                    <a class="delete-cert" href="{{ path('dw_user_dashboard_profile_certification_delete',{'id': cert.id}) }}"><i class="fa fa-close"></i></a>
                                </a>
                            </div>
                        {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-6">
                    {{ form_widget(form.cv.path,{'attr':{'class':'inputfile novalidate'}}) }}
                    {{ form_label(form.cv.path, '', {'label_attr':{'class':'button'}}) }}
                    {{ form_errors(form.cv.path) }}
                </div>
                <div class="col-md-6">
                    {% if user.cv %}
                        {% if user.cv.webPath|slice(-3) == 'pdf' %}
                        <a class="icon-pdf" href="{{ asset(user.cv.webPath) }}" target="_blank">
                            <img alt="pdf" src="{{ asset('images/pdf.png') }}">
                        </a>
                        {% else %}
                            <a class="icon-doc" href="{{ asset(user.cv.webPath) }}" target="_blank">
                                <img alt="doc" src="{{ asset('images/docx.png') }}">
                            </a>
                        {% endif %}
                    {% endif %}
                    {#<table class="table table-responsive table-hover table-bordered">
                        {% if user.cv %}
                            <tr>
                                <td>
                                    <a target="_blank" href="{{ asset(user.cv.webPath) }}">{{ user.cv.cv }}</a>
                                    <a href="{{ path('dw_user_dashboard_profile_curriculum_delete',{'id': user.cv.id}) }}"><span class="pull-right"><i class="fa fa-close"></i> </span> </a>
                                </td>
                            </tr>
                        {% endif %}
                    </table>#}
                </div>
            </div>


            </div>


        </div>
    </div>
    <button type="submit" class="button margin-top-15">{{ 'profile.edit.submit'|trans }}</button>
    {{ form_end(form) }}
{#{% render(controller('DWUserBundle:Dashboard/Profile:curriculum')) %}#}
{% endblock %}


{% block javascripts %}
    {{ parent() }}

    <script type="text/javascript">
        // change profile image
        $('#certification_path').change(function(){
            var elm = $(this);
            var fReader = new FileReader();
            fReader.readAsDataURL(elm[0].files[0]);
            fReader.onloadend = function(event){
                var img = $("#image_file");
                img.attr('src',event.target.result);
            }
        });
    </script>
{% endblock %}

src/DW/UserBundle/Resources/views/Dashboard/Profile/curriculum.html.twig
{% trans_default_domain 'dw_user' %}

{{ form_start(form) }}
<div class="dashboard-list-box margin-top-20">
    <h4 class="gray">Curriculum Vitae</h4>
    <div class="dashboard-list-box-static">

        <!-- Details -->
        <div class="my-profile">


            {{ form_row(form.path) }}


        </div>

        <button type="submit" class="button margin-top-15">{{ 'profile.edit.submit'|trans }}</button>

    </div>
</div>
{{ form_end(form) }}

src/DW/UserBundle/Resources/views/Dashboard/Profile/edit_about_me.html.twig
{% extends '@DWCore/Dashboard/Listing/layout.html.twig' %}

{% trans_default_domain 'dw_user' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('js/vendor/croppie/croppie.css') }}">
    <link rel="stylesheet" href="{{ asset('js/vendor/croppie/demo.css') }}">
{% endblock %}
{% block nav_dashboard -%}
    {% set nav_dashboard_current = 'profile' %}
    {{ parent() }}
{%- endblock %}

{% block page_header %}
    {% include "DWCoreBundle:Dashboard/Common:_page_header.html.twig" with {
    'title': 'nav.dashboard.profile.link'|trans({}, 'dw'),
    'sub': 'user.edit.completion_notice'|trans,
    'crumb': 'user.about.title'|trans
    } only %}
{% endblock %}

{% block nav_side_dashboard -%}
    {% include '@DWUser/Dashboard/Profile/_nav_side.html.twig' with {
    'nav_side_dashboard_current': 'about_me'
    } only %}
{%- endblock %}
{% set user_image = user.image ? user.image.webPath : UserImageConstants.IMAGE_FOLDER ~ UserImageConstants.IMAGE_DEFAULT %}


{% block content_dashboard %}

{{ form_start(form, {'attr': {'class': 'form-area'}}) }}

{% include 'DWCoreBundle:Frontend/Common:_flash.html.twig' %}

<div class="dashboard-list-box margin-top-0">
    <h4 class="gray">{{ 'nav.user.about_me.link'|trans }}</h4>
    <div class="dashboard-list-box-static">

        <!-- Details -->
        <div class="my-profile">
            {{ form_errors(form) }}
            <div class="row with-forms">
                <div class="col-md-12">
                    <label class="required">
                        Avatar
                        <span>*</span></label>
                </div>
                <div class="col-md-offset-1 col-md-4 upload-demo">

                    <div class="upload-msg">
                        <img id="avatar" src="{{ user_image }}"/>
                    </div>
                    <div class="upload-demo-wrap margin-bottom-95">
                        <div id="upload-demo"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="col-md-offset-1 col-md-4 upload-demo">
                    {{ form_errors(form.image.file ) }}
                    {{ form_errors(form.image.crop_img ) }}
                    <div class="actions">
                        <a class="btn file-btn">
                            <span><i class="fa fa-upload"></i> {{ 'profile.avatar.upload'|trans }}</span>
                            {{ form_widget(form.image.file,{'attr': {'class': 'upload novalidate', 'accept':'image/*'}} ) }}
                            {{ form_widget(form.image.crop_img ) }}
                        </a>
                        <a class="btn upload-result"><i class="fa fa-eye"></i> {{ 'profile.avatar.crop'|trans }}</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">{{ form_row(form.lastName) }}</div>
                <div class="col-md-6">{{ form_row(form.firstName) }}</div>
            </div>

            <label class="margin-top-0">{{ form_label(form.birthday) }}</label>
            <div class="row">
                <div class="col-md-4">{{ form_widget(form.birthday.day) }}</div>
                <div class="col-md-4">{{ form_widget(form.birthday.month) }}</div>
                <div class="col-md-4">{{ form_widget(form.birthday.year) }}</div>
            </div>
            {{ form_errors(form.birthday) }}

            <div class="row">
                <div class="col-md-4">{{ form_row(form.nationality) }}</div>
                <div class="col-md-4">{{ form_row(form.countryOfResidence) }}</div>
                <div class="col-md-4">{{ form_row(form.profession) }}</div>
            </div>

            <div class="row">
                {#<label>{{ 'profile.languages.title'|trans }}</label>#}
                <div class="col-md-12 languages-block">
                    {#Vous pouvez choisir plusieurs langues#}
                    {{ form_row(form.language) }}
                    <span class="help-block">{{ 'profile.languages.desc'|trans }}</span>
                    <a type="button" class="button border btn btn-default btn-add">
                        {{ 'profile.languages.add'|trans }}
                    </a>

                    <div class="list-inline btns-list languages margin-top-10"
                        data-prototype="{{ form_widget(form.languages.vars.prototype)|e }}">
                        {% if form.languages %}
                            {% for language in form.languages %}
                                <button id="{{ language.code.vars.value | language_name(app.request.locale) }}" class="btn btn-default" onclick="removeLanguage(this);">
                                    <i class="fa fa-times"></i>&nbsp;
                                    {{ language.code.vars.value | language_name(app.request.locale) }}
                                    {{ form_row(language,{'attr':{'row_class':'margin-bottom-0'}}) }}
                                </button>
                            {% endfor %}
                        {% else %}
                            {{ form_row(language,{'attr':{'row_class':'margin-bottom-0'}}) }}
                        {% endif %}
                    </div>

                </div>
            </div>

            <div class="row">
                {#<label>{{ 'profile.moreinfo.title'|trans }}</label>#}
                <div class="col-md-12">{{ form_row(form.description) }}</div>
            </div>

        </div>
    </div>
</div>

<button type="submit" class="button margin-top-15">{{ 'profile.edit.submit'|trans }}</button>

{{ form_end(form) }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('js/vendor/croppie/exif.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/vendor/croppie/croppie.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/vendor/croppie/custom.js') }}"></script>
{% endblock %}

src/DW/UserBundle/Resources/views/Dashboard/Profile/profile_switch.html.twig
{{ form_start(form) }}
<fieldset>
    <legend class="hidden">formswitchers</legend>
    <span class="title">
        <label for="applicant">
            {{ 'Asker'|trans }}
            {% if (nbMessages[0]['asker'] > 0 ) %} ({{ nbMessages[0]['asker'] }}) {% endif %}
        </label>
    </span>

    <div class="radio-holder">
        {{ form_widget(form['profile'][0],  {'id': 'applicant'}) }}
        {{ form_widget(form['profile'][1],  {'id': 'provider'}) }}
    </div>
    <strong class="counter">
        <label for="provider">{{ 'Offerer'|trans }}
            {% if (nbMessages[0]['offerer'] > 0) %} ({{ nbMessages[0]['offerer'] }}) {% endif %}
        </label>
    </strong>
    <input type="submit" class="hidden">
</fieldset>
{{ form_end(form) }}